### ISSUE TITLE
Additional methods

### ISSUE THREAD

**Issue by frank-pet** [ljmerza/py-our-groceries#10]
I added a few methods for  a project I  am working.  Offered back to you for inclusion in a future version.  Diff on pypi version 1.3.6 follows, updated source attached.
10c10
< 
---
> __version__ = "1.3.6+mods"
29a30,31
> ACTION_GET_MASTER_LIST = "getMasterList"
> ACTION_GET_CATEGORY_LIST = "getCategoryList"
34c36
< ACTION_ITEM_RENAME = 'changeItemValue'
---
> ACTION_ITEM_CHANGE_VALUE = 'changeItemValue'
38a41
> ACTION_LIST_DELETE_ALL_CROSSED_OFF = 'deleteAllCrossedOffItems'
43a47
> REGEX_MASTER_LIST_ID = r'href="list/(.*)">Manage master list</a>'
47a52
> ATTR_CATEGORY_ID = 'categoryId'
52a58
> ATTR_ITEM_NEW_VALUE = 'newValue'
56a63
> 
106a114,115
>                 self._master_list_id = re.findall(REGEX_MASTER_LIST_ID,
>                                                   responseText)[0]
111a121,132
>     async def get_master_list(self):
>         """Get an our grocery list's items."""
>         _LOGGER.debug('ourgroceries get_list_items')
>         other_payload = {ATTR_LIST_ID: self._master_list_id}
>         return await self._post(ACTION_GET_LIST, other_payload)
> 
>     async def get_category_list(self):
>         """Get our grocery lists."""
>         _LOGGER.debug('ourgroceries get_master_list')
>         other_payload = {ATTR_TEAM_ID: self._team_id}
>         return await self._post(ACTION_GET_CATEGORY_LIST, other_payload)
> 
149a171,179
>     async def delete_list(self, list_id):
>         """Create a new shopping list."""
>         _LOGGER.debug('ourgroceries create_list')
>         other_payload = {
>             ATTR_LIST_ID: list_id,
>             ATTR_TEAM_ID: self._team_id,
>         }
>         return await self._post(ACTION_LIST_REMOVE, other_payload)
> 
169a200,221
> 
>     async def add_item_to_master_list(self, value, category_id):
>         """Add a new item to a list."""
>         _LOGGER.debug('ourgroceries add_item_to_list')
>         other_payload = {
>             ATTR_LIST_ID: self._master_list_id,
>             ATTR_ITEM_VALUE: value,
>             ATTR_CATEGORY_ID: category_id,
>         }
>         return await self._post(ACTION_ITEM_ADD, other_payload)
> 
>     async def change_item_on_list(self, list_id, item_id, category_id, value):
>         """Add a new item to a list."""
>         _LOGGER.debug('ourgroceries add_item_to_list')
>         other_payload = {
>             ATTR_ITEM_ID: item_id,
>             ATTR_LIST_ID: list_id,
>             ATTR_ITEM_NEW_VALUE: value,
>             ATTR_CATEGORY_ID: category_id,
>             ATTR_TEAM_ID: self._team_id,
>         }
>         return await self._post(ACTION_ITEM_CHANGE_VALUE, other_payload)
177a230,237
> 
>     async def delete_all_crossed_off_from_list(self, list_id):
>         """delete all crossed off itemsn from a list."""
>         _LOGGER.debug('ourgroceries remove_item_from_list')
>         other_payload = {
>             ATTR_LIST_ID: list_id,
>         }
>         return await self._post(ACTION_LIST_DELETE_ALL_CROSSED_OFF, other_payload)

[ourgroceries.zip](https://github.com/ljmerza/py-our-groceries/files/5982506/ourgroceries.zip)

**Comment by ljmerza** [comment]
thanks add PR here https://github.com/ljmerza/py-our-groceries/pull/12
