### ISSUE TITLE
Hassio cummunity add-on requires lxml==4.4.0

### ISSUE THREAD

**Issue by pgsylvestre** [ljmerza/py-our-groceries#6]
consider updating dependencies to resolve usage in other projects
lxml==4.4.0
aiohttp==3.6.1

https://github.com/ljmerza/ha-our-groceries/issues/12#issuecomment-605387789

**Comment by pironic** [comment]
solved... consider closing this issue: https://github.com/ljmerza/py-our-groceries/pull/5

we just need https://github.com/ljmerza/ha-our-groceries/pull/13 to be merged, but that's not part of this repo.
